namespace VTuberSystemBase.CameraSwitcherTab.Contracts
{
    /// <summary>
    /// Event payload for <see cref="CameraIpcTopics.CameraCommand"/>
    /// (<c>camera/command</c>, design.md L1265). UI is the producer; the main-output
    /// side is the consumer. Operations:
    /// <list type="bullet">
    /// <item><c>add</c> — request creation of a new camera. <see cref="Type"/> required,
    /// <see cref="DisplayName"/> optional. <see cref="ClientRequestId"/> is correlated
    /// with the eventual <see cref="CameraCreatedEventPayload"/> /
    /// <see cref="CameraErrorEventPayload"/>.</item>
    /// <item><c>delete</c> — request deletion. <see cref="CameraId"/> required.</item>
    /// <item><c>active-set</c> — request active-camera switch. <see cref="CameraId"/>
    /// required.</item>
    /// </list>
    /// </summary>
    public readonly struct CameraCommandPayload
    {
        /// <summary>One of <c>add</c> / <c>delete</c> / <c>active-set</c>.</summary>
        public string Op { get; init; }

        /// <summary>GUID generated by the UI; echoed back in created/error events.</summary>
        public string ClientRequestId { get; init; }

        /// <summary>Required for <c>delete</c> / <c>active-set</c>; absent for <c>add</c>.</summary>
        public string? CameraId { get; init; }

        /// <summary>Required for <c>add</c> (<see cref="CameraTypeNames"/>).</summary>
        public string? Type { get; init; }

        /// <summary>Optional human-readable name; the UI may omit and the main side picks a default.</summary>
        public string? DisplayName { get; init; }
    }

    /// <summary>String constants for <see cref="CameraCommandPayload.Op"/>.</summary>
    public static class CameraCommandOps
    {
        public const string Add = "add";
        public const string Delete = "delete";
        public const string ActiveSet = "active-set";
    }
}
